### ISSUE TITLE
validate swap timeouts set (as an xmr-maker)

### ISSUE THREAD

**Issue by noot** [AthanorLabs/atomic-swap#161]
since the xmr-taker can decide what timeouts to set in the swap contract, the xmr-maker needs to validate these and check that they're not unreasonably short or long.

**Comment by dimalinux** [comment]
Can clarify/document this more concretely?

Questions:

Does Alice have flexibility in the duration she passes when executing the `newSwap` transaction?
If not, should the timeout be set at contract creation time instead of at swap creation?

Assuming Alice has to use a specific duration but we don't fix it at contract creation time, Bob has to check 2 things:
(1) That T1-T0 is the exact duration that Alice was required to set when creating the swap.
(2) That Alice didn't wait "too long" after creating the swap, but before sending the info to Bob.

Does that sound right? And Alice needs to use a duration of 1 hour in stagenet/mainnet and "too long" is 1/20th of the duration or 3 minutes? (I'm basing that off of the current PR.)

**Comment by noot** [comment]
@dimalinux yes, Alice has the ability to put a specific timeout. I'd rather not put it at contract creation because different networks may require different values. 

yeah basically, we want to make sure Alice didn't put some bad timeout values (too short or too long), that would result in our funds being locked for too long or not give us enough time to enact all protocol steps.

yep exactly, I somewhat arbitrarily chose the 3 minute time as it shouldn't take Alice longer than that to confirm the `newSwap` tx and send a network message. it should actually be less than a minute, but I added some buffer time.
