### ISSUE TITLE
check transaction hash in `handleNotifyXMRLock`

### ISSUE THREAD

**Issue by noot** [AthanorLabs/atomic-swap#164]
in addition or instead of checking balances in `xmrtaker.handleNotifyXMRLock`, we should also receive and check the lock transaction via its hash.

**Comment by dimalinux** [comment]
Here is a rough-draft proposal on how we should handle the Monero transactions. We may want to tune the confirmation count formulas or just go with fixed values that don't depend on the swap amount. I just wanted to get the discussion going below.

# Monero Transactions During a Swap
There are 2 Monero transactions that happen during a swap:

1. Bob uses [`transfer`](https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#transfer) to send XMR to the A+B wallet address. Alice verifies this transaction after being notified by Bob that the funds were sent.
2. Alice uses [`sweep_all`](https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#sweep_all) to move all funds from the A+B Spend wallet to her primary wallet.

## Bob sending to the A+B address

The `transfer` method gets the transaction into the mempool. It does not wait for the transaction to be mined. Question: What are Bob's obligations? Our goal is to keep the swap state machine simple and safe.

Proposal:
* Bob MUST send the TX ID and the TX KEY when notifying that his XMR is locked.
* Bob SHOULD wait for `min(ceiling(amount-in-XMR) + 2, 12)` confirmations before notifying Alice if he doesn't want to have the swap cancelled.
* Alice SHOULD verify that the transaction has `min(ceiling(amount-in-XMR), 10)` confirmations using [`check_tx_key`](https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#check_tx_key). Note that Bob waits for 2 additional confirmations over what Alice verifies so that swaps are not needlessly cancelled due to network synchronization delays. If the transaction has insufficient confirmations, Alice will immediately refund her ETH to cancel the swap.
* Bob SHOULD NOT set the `unlock_time` field transferring funds to the A+B address. He could, technically, set the field, then wait for its requirements to expire before notifying Alice, but using this field for normal transfers is [a horrible idea](https://thecharlatan.ch/Monero-Unlock-Time-Privacy/) and [probably be removed](https://github.com/monero-project/research-lab/issues/78).
* In addition to checking the amount and destination address using `check_tx_key`, Alice also creates an A+B View-only wallet and checks the `unlocked_balance` amount on it. If the unlocked balance is not equal or greater than what Bob was supposed to send, Alice SHOULD immediately request an ETH refund to cancel the swap. Unfortunately, this extra step is required to make sure that Bob didn't send the funds, but prevent Alice from using them in her lifespan.

## Alice Sweeps the XMR from the A+B Spend wallet

As with the `transfer` wallet method, [`sweep_all`](https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#sweep_all) only relays the transaction into the mempool without waiting for it to be mined. Question: How long should Alice wait before deciding that the swap is complete enough to remove recovery information?

Proposal:
Alice waits for `min(ceiling(amount-in-XMR), 10)` confirmations on the sweep transaction before deciding that the swap is complete enough to perform cleanup on.
