### ISSUE TITLE
implement suggested exchange rate feature

### ISSUE THREAD

**Issue by noot** [AthanorLabs/atomic-swap#205]
currently, to make an offer, you must provide an exchange rate for the swap. this requires the user to manually calculate it themselves. it would be nice to add a subcommand for fetching a suggested exchange rate from an external API (coingecko or something like that?) this *would* be pretty centralized (unless we hit up many APIs and average them), so this should also notify the user to double check that they're okay with the rate.

**Comment by doonte** [comment]
Chainlink has oracle services for aggregated on-chain data feeds that are easy to query from an Ethereum node: https://data.chain.link/ethereum/mainnet

Since we already require access to an Ethereum node, this might be a reasonably decentralized solution that in addition minimizes any privacy issues. There is an [XMR-USD feed](https://data.chain.link/ethereum/mainnet/crypto-usd/xmr-usd) we could use.

The XMR-USD feed is updated every time the price deviates by 1% or every 24 hours and just requires a call to `latestRoundData()` at contract [0xFA66458Cce7Dd15D8650015c4fce4D278271618F](https://etherscan.io/address/0xfa66458cce7dd15d8650015c4fce4d278271618f).

**Comment by noot** [comment]
@doonte  thanks for this! will definitely look into those.
