### ISSUE TITLE
dockerize swapd

### ISSUE THREAD

**Issue by noot** [AthanorLabs/atomic-swap#206]
there have been some build issues noted on M1 (and potentially other platforms also). we should offer a docker image of swapd so it can easily be built and run on various platforms.

**Comment by mewmix** [comment]
as one of those m1 users with issues, I made a docker container to test local swaps, and have successfully stepped through the whole process. Can I open a PR with it? 
<img width="882" alt="Screen Shot 2023-03-24 at 12 17 10 PM" src="https://user-images.githubusercontent.com/42463809/227620929-cfe92b5e-2c15-46c5-9861-502552e573b4.png">


`FROM golang:1.19 AS build

RUN apt-get update && apt-get install -y \
    curl \
    git \
    build-essential \
    libboost-all-dev \
    bzip2 \
    nano \
    jq 

WORKDIR /app

RUN git clone https://github.com/AthanorLabs/atomic-swap.git

WORKDIR /app/atomic-swap

RUN make build


FROM node:latest

WORKDIR /app

COPY --from=build /app/atomic-swap /app/atomic-swap

RUN npm install --global ganache

WORKDIR /app/atomic-swap`

**Comment by dimalinux** [comment]
Part of the reason this ticket hasn't been done yet, is that we don't yet have a clear specification on what the end dockerized product should look like to help the most users. Can we spend some time here doing that before creating the PR? @mewmix, you probably have some good ideas to share since you have already run it in docker.

We'll eventually produce release binaries for users that do not want to install Go and build it themselves. I was thinking the docker container might be built from a separate repository in `AthanorLabs`, and that we would use the separate repo for building what gets uploaded to Dockerhub. Isn't that how most other projects manage their docker images?

For `swapd` use, I was thinking most people would want to run the container in a way that mounts the `--data-dir`, where the wallets and swap database are stored, either from the filesystem or from an external volume. People may or may not want to run `swapcli` outside the container. We can produce static binaries and `swapcli`, which is much simpler than `swapd`, could, potentially, be built for a larger number of platforms for those that want to run it outside a container. For `swapcli`, would people want to run it from a separate container, where it is the default binary, or would they prefer just one container that has both? Related: Will we be setting CMD, ENTRYPOINT or both inside the container?

Another view might be that we don't need dockerhub, and all we need is a script for users to build their own container plus an additional readme in the docs directory on how to use it.

Let's spend some time brainstorming here on what the end goals is. @mewmix let us know how you would like to use the docker container with mainnet swaps. Or is the goal primarily for testing? If I was using it for testing, I would probably use docker-compose and run ganache from the official ganache container: https://hub.docker.com/r/trufflesuite/ganache

**Comment by mewmix** [comment]
Primarily my goal with the container was getting up to speed with the working parts of the repo and mitigating my install & configuration time to then reproduce & test all the steps of local swapping, then migrate to a different evm network outside of goerli, speaking of do I need to set the chain id via a flag? I see it expects goerli when I use the stagenet environment.


I think a minimal docker image for testing would be nice and then a more streamlined maker/taker container for people looking to host instances would be good eventually. 

Good call on the ganache docker image, didn't know about it honestly !

**Comment by dimalinux** [comment]
@mewmix wrote:
> do I need to set the chain id via a flag

We no longer have a flag to set the chain ID. It is now set automatically by querying the ethereum endpoint for it. Which network do you want to use? Sepolia testnet? If that's the one, we can quickly make the code modification to allow both goeri and sepolia endpoints when using `--env=stagenet`, but we probably only have the resources to maintain bootnodes for one or the other.

Since this is getting off of the topic of docker, can you join us in Matrix chat (https://matrix.to/#/#ethxmrswap:matrix.org) or create a separate issue to support a specific evm network?
