### ISSUE TITLE
check ethereum chain ID on startup

### ISSUE THREAD

**Issue by noot** [AthanorLabs/atomic-swap#261]
we should check that the chain ID as returned from the provided ETH endpoint matches the expected network based on the environment.

**Comment by phazejeff** [comment]
i'll work on this one, what would be the expected chain ID for development environment?

**Comment by dimalinux** [comment]
It is ganache, which should be 1337. Part of this task should be giving thought on how to improve the organization of the code.  We check the monero config relative to the environment in `validateMonerodConfig` of the `monero` package. Our extended ethclient package (`extethclient`) doesn't currently have functions that use the environment.

**Comment by phazejeff** [comment]
I added a `validateEthClient` in the `extethclient` package in the branch linked below. i also am passing in the environment to the `NewEthClient` in order to validate the eth client within that function. In terms of organization, something like this?

https://github.com/phazejeff/atomic-swap/commit/73040988ddd246a557e9b2ac382a996782ff3e15

**Comment by dimalinux** [comment]
Yeah, something like that is probably the way to go. Use your best judgement and we can add commentary when the PR is up. Make sure to add a unit test, at minimum, for dev mode. Make sure that `make lint-go` runs successfully. The current code won't work because it is doing pointer comparisons instead of value comparisons. You probably want some constants for the chain IDs and decide if the validate function needs to be exported from the package or not.

**Comment by phazejeff** [comment]
PR #276
