### ISSUE TITLE
Rename swap contract

### ISSUE THREAD

**Issue by doonte** [AthanorLabs/atomic-swap#346]
Usually in Ethereum naming, a factory contract is a contract that creates other contracts, often very similar ones. Since the swap contract does not create new contracts, I think we should rename "SwapFactory" to something more descriptive. "AtomicSwap" or "MoneroAtomicSwap" are my suggestions.

**Comment by noot** [comment]
Agreed, it isn't a factory in the normal sense. I'm good with just `AtomicSwap.sol`

**Comment by dimalinux** [comment]
My only hesitation about the name `AtomicSwap` is that the current name, `SwapFactory`,  gives a clear distinction between itself and the `Swap` struct that we define nested inside it. The distinction is even more important in code that uses the auto-generated go bindings where we'd like a delineation between the contract-bound object and the swap objects it creates.

Here's a few more ideas to get the ball rolling.
* SwapCreator
* SwapMachine
* SwapForge
* SwapAthanor
* AtomicMachine

I'm fine with any of them and can even make `AtomicSwap` work, but I wanted to make sure we considered any downsides in code readability. Or that, in order to maintain readability, we'd need more custom code changes than query/replace changes.

**Comment by noot** [comment]
`SwapCreator` seems good, I'd also suggest `SwapManager` potentially? will give it some more thought.

**Comment by dimalinux** [comment]
`SwapManager` might be problematic, as we are already using the name in our code:
https://github.com/search?q=repo%3AAthanorLabs%2Fatomic-swap+swapManager&type=code

**Comment by doonte** [comment]
I think `SwapCreator` or `AtomicSwapCreator` or `SwapEngine`/`AtomicSwapEngine` would be nice.

**Comment by noot** [comment]
closed with #372
