### ISSUE TITLE
remove hardcoded forwarder address for network config; load from swap contract

### ISSUE THREAD

**Issue by noot** [AthanorLabs/atomic-swap#365]
as title says, we can remove the `ForwarderContractAddress` from the network configs and just load it from the contract at `SwapFactoryAddress`.

**Comment by dimalinux** [comment]
@stubbrn This ticket was created before @noot found out that the forwarder contract, that we haven't modified, is already deployed on `mainnet` and `sepolia`. I think our new plan of using the existing, deployed contract changes this ticket a little.

I'm not sure we've fully sussed out what the behavior should be. The options I see are:
1. Continue with the plan described in this ticket and not store the forwarder address. This would require our bytecode check to work, but right now the bytecode of the forwarder contract in dev deployments will not match what is deployed on mainnet/sepolia, because we compiled the contract with a slightly newer version of solidity in the `go-relayer` repo. To use this solution, we need to change the `go-relayer` repo to use the same solc version that was used in the existing deployed contracts.
2. Continue to store the forwarder addresses in the config structures. If the address of the forwarder in the Taker's SwapCreator contract matches the value in our config, we just accept it, otherwise we do a bytecode check. When we get the forwarder compiled with the correct version of solc in `go-relayer`, we can add bytecode checks of the hard-coded addresses in the configs to unit tests for sepolia/mainnet.

**Comment by dimalinux** [comment]
These PRs handle the ticket:
https://github.com/AthanorLabs/go-relayer/pull/13
https://github.com/AthanorLabs/atomic-swap/pull/427

The solution I went with was to have the `go-relayer` project control the constants for mainnet/sepolia forwarder contracts. Right now the code will optimize and skip the byte-code comparison on mainnet/sepolia if the contract addresses are an exact match. We also have unit tests to guarantee that this is safe. If we are on dev, or if the addresses do not match, we compare the bytecode. There could be an argument to only accept an exact address match on mainnet/sepolia to avoid a contract construction attack.
